/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Voucher } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'Tất cả sản phẩm', emoji: '🛍️' },
  { id: 'racket', name: 'Vợt cầu lông', emoji: '🏸', imageUrl: 'https://images.unsplash.com/photo-1708312604109-16c0be9326cd?auto=format&fit=crop&w=400&q=80' },
  { id: 'shoes', name: 'Giày cầu lông', emoji: '👟', imageUrl: 'https://images.unsplash.com/photo-1748323850805-5d6e76e59639?auto=format&fit=crop&w=400&q=80' },
  { id: 'shirt', name: 'Áo cầu lông', emoji: '👕', imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80' },
  { id: 'skirt', name: 'Váy cầu lông', emoji: '👗', imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80' },
  { id: 'pants', name: 'Quần cầu lông', emoji: '🩳', imageUrl: 'https://images.unsplash.com/photo-1748323850805-5d6e76e59639?auto=format&fit=crop&w=400&q=80' },
  { id: 'bag', name: 'Túi cầu lông', emoji: '🎒', imageUrl: 'https://images.unsplash.com/photo-1672223303533-68e945a1385c?auto=format&fit=crop&w=400&q=80' },
  { id: 'backpack', name: 'Balo cầu lông', emoji: '🎒', imageUrl: 'https://images.unsplash.com/photo-1672223303533-68e945a1385c?auto=format&fit=crop&w=400&q=80' },
  { id: 'accessories', name: 'Phụ kiện cầu lông', emoji: '🏸', imageUrl: 'https://images.unsplash.com/photo-1721760886713-1ab0c5045bf7?auto=format&fit=crop&w=400&q=80' }
] as const;

export const BRANDS = ['Victor', 'Yonex', 'Lining', 'Mizuno', 'Kumpoo', 'Felet'] as const;

export const AVAILABLE_TENSIONS = [
  'Mua khung chưa đan (Không căng)',
  'Căng sẵn 9.5 kg (Người mới, lực tay yếu)',
  'Căng sẵn 10.0 kg (Lực tay trung bình - yếu)',
  'Căng sẵn 10.5 kg (Lực tay trung bình khá)',
  'Căng sẵn 11.0 kg (Lực tay tốt, chơi phong trào khá)',
  'Căng sẵn 11.5 kg (Lực tay khỏe, nâng cao)',
  'Căng sẵn 12.0 kg (Lực tay rất khỏe, vận động viên)'
];

export const VOUCHERS: Voucher[] = [
  {
    code: 'FREESHIP499',
    description: 'Miễn phí vận chuyển toàn quốc cho đơn hàng từ 499.000đ',
    discountType: 'fixed',
    discountValue: 30000,
    minOrderValue: 499000
  },
  {
    code: 'VIETBAD50',
    description: 'Giảm ngay 50.000đ cho đơn hàng từ 1.000.000đ',
    discountType: 'fixed',
    discountValue: 50000,
    minOrderValue: 1000000
  },
  {
    code: 'VIPBAD10',
    description: 'Giảm 10% tổng hóa đơn (tối đa 150.000đ) cho Voucher đặc biệt',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 800000
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Vợt cầu lông Victor TK-HMR Pro (Thruster K Hammer Pro)',
    brand: 'Victor',
    category: 'racket',
    categoryName: 'Vợt cầu lông',
    price: 2390000,
    oldPrice: 2990000,
    rating: 4.8,
    reviewsCount: 42,
    imageEmoji: '🏸',
    imageUrl: '/products/p1-v2.jpg',
    galleryImages: ['/products/gallery/p1-gallery-1.webp', '/products/gallery/p1-gallery-2.webp', '/products/gallery/p1-gallery-3.webp', '/products/gallery/p1-gallery-4.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 20,
    specs: {
      weight: '4U (Khoảng 83g)',
      balance: 'Nặng đầu',
      tension: '20 - 28 lbs (Tối đa 12.5 kg)',
      stiffness: 'Trung bình',
      material: 'Graphite cứng cáp kết hợp Nano Resin gia cường lực đẩy',
      origin: 'Chính hãng Victor - Sản xuất tại Đài Loan'
    },
    description: 'Victor Thruster K Hammer Pro là cây vợt thiên công mạnh mẽ thích hợp cho người chơi phong trào yêu thích đập cầu từ phía sau. Khung vợt thiết kế khí động học giúp vung vợt cực nhanh, tạo lực nhấn khủng khiếp.'
  },
  {
    id: 'p2',
    name: 'Giày cầu lông Yonex Power Cushion 65Z3 Wide - Trắng Vàng',
    brand: 'Yonex',
    category: 'shoes',
    categoryName: 'Giày cầu lông',
    price: 1890000,
    oldPrice: 2300000,
    rating: 4.9,
    reviewsCount: 56,
    imageEmoji: '👟',
    imageUrl: '/products/p2.jpg',
    galleryImages: ['/products/gallery/p2-gallery-1.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 17,
    specs: {
      weight: 'Khoảng 310g / chiếc',
      balance: 'Form chân bè 3E',
      material: 'Đế cao su Radial Blade, lớp lót Power Cushion siêu êm',
      stiffness: 'Chống lật cổ chân và bảo vệ khớp gối chuyên sâu',
      origin: 'Chính hãng Yonex - Nhập khẩu Nhật Bản'
    },
    description: 'Dòng giày quốc dân huyền thoại được sử dụng bởi hàng loạt các tay vợt đẳng cấp thế giới. Công nghệ Power Cushion hấp thụ chấn rung cực mạnh và chuyển hóa thành động lực cho bước di chuyển tiếp theo.'
  },
  {
    id: 'p3',
    name: 'Túi cầu lông Victor BR9213 Đa Năng 2 Ngăn Lớn',
    brand: 'Victor',
    category: 'bag',
    categoryName: 'Túi cầu lông',
    price: 790000,
    oldPrice: 990000,
    rating: 4.7,
    reviewsCount: 28,
    imageEmoji: '🎒',
    imageUrl: '/products/p3.jpg',
    galleryImages: ['/products/gallery/p3-gallery-1.webp', '/products/gallery/p3-gallery-2.webp', '/products/gallery/p3-gallery-3.webp', '/products/gallery/p3-gallery-4.webp'],
    isSale: true,
    discountPercent: 20,
    specs: {
      weight: 'Chất liệu vải Polyester + PVC chống thấm nước hiệu quả',
      balance: 'Đựng tối đa 6 - 8 cây vợt cùng phụ kiện và quần áo',
      tension: 'Có ngăn chứa giày riêng biệt thoáng khí chống mùi',
      origin: 'Chính hãng Victor'
    },
    description: 'Thiết kế hiện đại, phối màu cá tính mang phong cách trẻ trung thể thao năng động. Quai đeo có đệm xốp êm vai, hỗ trợ mang xách thuận tiện di chuyển trong thời gian dài.'
  },
  {
    id: 'p4',
    name: 'Dây cước căng vợt Yonex BG 65 Titanium Siêu Bền',
    brand: 'Yonex',
    category: 'accessories',
    categoryName: 'Phụ kiện cầu lông',
    price: 180000,
    oldPrice: 220000,
    rating: 4.8,
    reviewsCount: 120,
    imageEmoji: '🧵',
    imageUrl: '/products/p4.png',
    isNew: true,
    isSale: true,
    discountPercent: 18,
    specs: {
      weight: 'Đường kính sợi: 0.70 mm',
      balance: 'Độ nảy cầu: 7/10 | Độ bền sợi: 10/10',
      stiffness: 'Cảm giác chạm cầu: Cứng trung bình',
      material: 'Được phủ một lớp hợp chất Titanium tăng cao độ chịu nhiệt và bền bỉ',
      origin: 'Chính hãng Yonex - Sản xuất tại Nhật Bản'
    },
    description: 'Cực kỳ phù hợp cho người chơi muốn tối ưu hóa chi phí nhờ sức bền vượt trội. Cước cho âm nổ đanh sinh động, giữ mức căng ổn định dài lâu.'
  },
  {
    id: 'p5',
    name: 'Vợt cầu lông Lining Axforce Cannon (Bản Rồng Lửa)',
    brand: 'Lining',
    category: 'racket',
    categoryName: 'Vợt cầu lông',
    price: 1490000,
    oldPrice: 1990000,
    rating: 4.9,
    reviewsCount: 88,
    imageEmoji: '🏸',
    imageUrl: '/products/p5.jpg',
    galleryImages: ['/products/gallery/p5-gallery-1.webp', '/products/gallery/p5-gallery-2.webp', '/products/gallery/p5-gallery-3.webp', '/products/gallery/p5-gallery-4.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 25,
    specs: {
      weight: '4U / 5U linh hoạt ứng biến lực tay',
      balance: 'Hơi nặng đầu 295mm',
      tension: 'Mức căng tối đa: 31 lbs (Lên tới 14kg siêu chịu lực)',
      stiffness: 'Thân vợt dẻo trung bình',
      material: 'Carbon cường độ cao hấp thụ xung lực tốt',
      origin: 'Chính hãng Lining - Nhập khẩu chính ngạch'
    },
    description: 'Cây vợt giá rẻ quốc dân làm mưa làm gió thị trường Việt Nam. Rất dễ thuần phục, hỗ trợ lực cực tốt dành cho cả các bạn nữ hoặc người mới tập chơi có lực cổ tay trung bình yếu.'
  },
  {
    id: 'p6',
    name: 'Áo thun cầu lông Yonex nhanh khô, khử mùi, thoáng khí',
    brand: 'Yonex',
    category: 'shirt',
    categoryName: 'Áo cầu lông',
    price: 299000,
    oldPrice: 399000,
    rating: 4.6,
    reviewsCount: 18,
    imageEmoji: '👕',
    imageUrl: '/products/p6.jpg',
    isSale: true,
    discountPercent: 25,
    specs: {
      weight: 'Chất liệu: 100% Polyester thun sọc xẻ kim cao cấp',
      balance: 'Công nghệ dệt lỗ thoáng thông minh độc quyền Very Cool',
      stiffness: 'Chống bám bụi, co giãn 4 chiều vận động linh hoạt',
      origin: 'Hàng VNXK cao cấp bền màu'
    },
    description: 'Thiết kế áo đấu chuẩn thi đấu cầu lông quốc tế. Trọng lượng siêu nhẹ, thoát mồ hôi chỉ trong 3 giây đem lại cảm giác mượt mà sảng khoái suốt trận đấu dài.'
  },
  {
    id: 'p7',
    name: 'Vợt cầu lông Yonex Astrox 88D Game (Chính hãng)',
    brand: 'Yonex',
    category: 'racket',
    categoryName: 'Vợt cầu lông',
    price: 3390000,
    oldPrice: 3890000,
    rating: 4.8,
    reviewsCount: 33,
    imageEmoji: '🏸',
    imageUrl: '/products/p7.png',
    galleryImages: ['/products/gallery/p7-gallery-1.webp', '/products/gallery/p7-gallery-2.webp', '/products/gallery/p7-gallery-3.webp', '/products/gallery/p7-gallery-4.webp'],
    isHot: true,
    specs: {
      weight: '4U (khoảng 83g)',
      balance: 'Nặng đầu chuyên tấn công áp đảo uy lực',
      tension: 'Tối đa 28 lbs (12.7 kg)',
      stiffness: 'Cứng',
      material: 'HM Graphite + Nanomesh Neo giúp uốn cong và phản hồi nhanh',
      origin: 'Chính hãng Yonex - Sản xuất tại Đài Loan'
    },
    description: 'Phiên bản cải tiến hướng tới đối tượng người chơi trung phong trào muốn sở hữu quả đập uy lực như tuyển thủ chuyên nghiệp nhưng dễ kiểm soát hơn bản Pro cường độ cao.'
  },
  {
    id: 'p8',
    name: 'Combo Tập Luyện Chuyên Nghiệp VietBad Starter',
    brand: 'Felet',
    category: 'accessories',
    categoryName: 'Phụ kiện cầu lông',
    price: 990000,
    oldPrice: 1590000,
    rating: 4.9,
    reviewsCount: 15,
    imageEmoji: '🎁',
    imageUrl: '/products/p8.jpg',
    isNew: true,
    isSale: true,
    discountPercent: 37,
    specs: {
      weight: 'Gồm: Vợt carbon Felet + túi đơn + 2 hộp cầu lông + 3 quấn cán cao su',
      balance: 'Vợt cân bằng công thủ toàn diện dễ chơi',
      tension: 'Hỗ trợ căng sẵn dây cước cước bền chắc',
      origin: 'Combo tuyển chọn chính hãng giá tốt'
    },
    description: 'Set đồ hoàn thiện nhất cho người bắt đầu tập chơi cầu lông. Bạn không cần băn khoăn lựa chọn riêng lẻ, mua combo tiết kiệm ngay 600K và sẵn sàng vác kiếm lên sân.'
  },
  {
    id: 'p9',
    name: 'Vợt cầu lông Kumpoo Power Control K520 Pro',
    brand: 'Kumpoo',
    category: 'racket',
    categoryName: 'Vợt cầu lông',
    price: 790000,
    oldPrice: 1100000,
    rating: 4.7,
    reviewsCount: 104,
    imageEmoji: '🏸',
    imageUrl: '/products/p9.jpg',
    galleryImages: ['/products/gallery/p9-gallery-1.webp', '/products/gallery/p9-gallery-2.webp', '/products/gallery/p9-gallery-3.webp', '/products/gallery/p9-gallery-4.webp'],
    isSale: true,
    discountPercent: 28,
    specs: {
      weight: '4U (khoảng 82g)',
      balance: 'Cân bằng công thủ toàn diện (290 ± 5mm)',
      tension: 'Chịu lực tối đa lên tới 28 lbs',
      stiffness: 'Thân hơi dẻo bền bỉ đàn hồi cực cao',
      origin: 'Chính hãng Kumpoo - Thương hiệu Nhật'
    },
    description: 'Dòng vợt nhập môn được yêu thích nhất mọi thời đại tại Việt Nam với nước sơn bền đẹp, khả năng chịu va chạm cạch cầu tối ưu giúp người tập luyện không lo sứt sẹo vợt.'
  },
  {
    id: 'p10',
    name: 'Giày Cầu Lông Mizuno Wave Claw EL 2 Siêu Nhẹ',
    brand: 'Mizuno',
    category: 'shoes',
    categoryName: 'Giày cầu lông',
    price: 2450000,
    oldPrice: 2950000,
    rating: 4.9,
    reviewsCount: 22,
    imageEmoji: '👟',
    imageUrl: '/products/p10.jpg',
    galleryImages: ['/products/gallery/p10-gallery-1.webp'],
    specs: {
      weight: 'Siêu nhẹ: Chỉ khoảng 275g / chiếc',
      material: 'Đế PoWnCe êm thoáng, lớp lót Mizuno Wave chống chấn động gối',
      balance: 'Form thường ôm khít chân bứt tốc cực tốt',
      origin: 'Chính hãng Mizuno - Thương hiệu cao cấp Nhật Bản'
    },
    description: 'Mizuno Wave Claw EL 2 chú trọng vào giảm trọng lượng đôi giày tới mức tối đa mà vẫn giữ đặc tính ổn định tuyệt đỉnh khi thực hiện các pha bật đổi hướng nhanh bất ngờ hóc hiểm.'
  },
  {
    id: 'p11',
    name: 'Quần Sọt Thể Thao Cầu Lông Li-Ning Thấm Hút Cao Cấp',
    brand: 'Lining',
    category: 'pants',
    categoryName: 'Quần cầu lông',
    price: 199000,
    oldPrice: 280000,
    rating: 4.7,
    reviewsCount: 31,
    imageEmoji: '👕',
    imageUrl: '/products/p11-v2.jpg',
    isSale: true,
    discountPercent: 29,
    specs: {
      weight: 'Chất liệu thun gai tổ ong thể thao chính hãng',
      balance: 'Cắt may 3D thoải mái bật nhảy không lo kích bó giật',
      origin: 'Chính hãng Li-Ning phân phối'
    },
    description: 'Quần ngắn cao cấp phối viền sọc cực chất. Co giãn tuyệt đối giúp người chơi bật cao smash không hề bị hạn chế cơ đùi.'
  },
  {
    id: 'p12',
    name: 'Váy cầu lông nữ Yonex 26068 dáng xòe có quần trong',
    brand: 'Yonex',
    category: 'skirt',
    categoryName: 'Váy cầu lông',
    price: 329000,
    oldPrice: 420000,
    rating: 4.8,
    reviewsCount: 24,
    imageEmoji: '👗',
    imageUrl: '/products/p12.jpg',
    isNew: true,
    isSale: true,
    discountPercent: 22,
    specs: {
      weight: 'Vải thun lạnh mềm nhẹ, co giãn 4 chiều',
      balance: 'Có quần bảo hộ bên trong, form xòe gọn dáng',
      material: 'Polyester thể thao thoáng khí, nhanh khô',
      origin: 'Hàng thể thao cao cấp'
    },
    description: 'Mẫu váy tập luyện và thi đấu cầu lông nữ với form xòe trẻ trung, có quần trong tiện lợi giúp vận động thoải mái trong từng pha bước chéo và bật nhảy.'
  },
  {
    id: 'p13',
    name: 'Váy cầu lông Lining Competition màu trắng xanh',
    brand: 'Lining',
    category: 'skirt',
    categoryName: 'Váy cầu lông',
    price: 359000,
    oldPrice: 480000,
    rating: 4.7,
    reviewsCount: 19,
    imageEmoji: '👗',
    imageUrl: '/products/p13.jpg',
    isSale: true,
    discountPercent: 25,
    specs: {
      weight: 'Chất vải nhẹ, không bám mồ hôi',
      balance: 'Lưng thun bản lớn ôm chắc khi di chuyển',
      material: 'Polyester pha spandex',
      origin: 'Lining tuyển chọn'
    },
    description: 'Váy cầu lông nữ phong cách thi đấu, dễ phối với áo đội tuyển hoặc áo polo tập luyện. Form linh hoạt, không cản trở các động tác bước thấp và đập cầu.'
  },
  {
    id: 'p14',
    name: 'Balo cầu lông Yonex Team Backpack 92212 xanh navy',
    brand: 'Yonex',
    category: 'backpack',
    categoryName: 'Balo cầu lông',
    price: 690000,
    oldPrice: 890000,
    rating: 4.8,
    reviewsCount: 36,
    imageEmoji: '🎒',
    imageUrl: '/products/p14.jpg',
    galleryImages: ['/products/gallery/p14-gallery-1.webp', '/products/gallery/p14-gallery-2.webp', '/products/gallery/p14-gallery-3.webp', '/products/gallery/p14-gallery-4.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 22,
    specs: {
      weight: 'Đựng 1-2 vợt, giày và quần áo tập',
      balance: 'Có ngăn giày riêng, dây đeo đệm êm vai',
      material: 'Polyester chống bám bụi, hạn chế thấm nước',
      origin: 'Chính hãng Yonex'
    },
    description: 'Balo tập luyện gọn nhẹ cho người đi sân hằng ngày. Khoang chứa vừa đủ dụng cụ cần thiết, thiết kế thể thao dễ mang khi đi học, đi làm hoặc tập luyện.'
  },
  {
    id: 'p15',
    name: 'Balo cầu lông Victor BR6013 chống thấm đa năng',
    brand: 'Victor',
    category: 'backpack',
    categoryName: 'Balo cầu lông',
    price: 760000,
    oldPrice: 960000,
    rating: 4.9,
    reviewsCount: 27,
    imageEmoji: '🎒',
    imageUrl: '/products/p15.jpg',
    isNew: true,
    isSale: true,
    discountPercent: 21,
    specs: {
      weight: 'Sức chứa rộng cho vợt, cầu, phụ kiện và laptop mỏng',
      balance: 'Dây đeo thoáng lưng, có đệm thoải mái',
      material: 'Vải tổng hợp dày dặn, dây kéo bền',
      origin: 'Chính hãng Victor'
    },
    description: 'Mẫu balo cầu lông phù hợp người chơi cần một chiếc túi gọn nhưng có sức chứa tốt. Kiểu dáng đứng form, dễ sắp xếp đồ và phụ kiện riêng biệt.'
  },
  {
    id: 'p16',
    name: 'Áo cầu lông Victor Training A102 thoáng khí màu xanh',
    brand: 'Victor',
    category: 'shirt',
    categoryName: 'Áo cầu lông',
    price: 269000,
    oldPrice: 360000,
    rating: 4.6,
    reviewsCount: 32,
    imageEmoji: '👕',
    imageUrl: '/products/p16.jpg',
    isSale: true,
    discountPercent: 25,
    specs: {
      weight: 'Vải lưới thể thao siêu nhẹ',
      balance: 'Form tiêu chuẩn dễ vận động',
      material: 'Polyester thoáng khí, nhanh khô',
      origin: 'Trang phục thể thao Victor'
    },
    description: 'Áo tập cầu lông dễ mặc hằng ngày, chất vải mềm và nhẹ, phù hợp tập luyện cường độ cao hoặc thi đấu phong trào.'
  },
  {
    id: 'p17',
    name: 'Áo polo cầu lông Kumpoo Elite đen đỏ',
    brand: 'Kumpoo',
    category: 'shirt',
    categoryName: 'Áo cầu lông',
    price: 319000,
    oldPrice: 430000,
    rating: 4.7,
    reviewsCount: 21,
    imageEmoji: '👕',
    imageUrl: '/products/p17.jpg',
    isNew: true,
    isSale: true,
    discountPercent: 26,
    specs: {
      weight: 'Cổ polo đứng form, không xệ vai',
      balance: 'Đường may chắc chắn cho thi đấu',
      material: 'Vải lạnh thể thao co giãn',
      origin: 'Kumpoo tuyển chọn'
    },
    description: 'Áo polo cầu lông có cổ lịch sự, phù hợp đi sân và sinh hoạt đội nhóm. Chất vải thoáng, không bị nặng áo khi ra mồ hôi nhiều.'
  },
  {
    id: 'p18',
    name: 'Quần cầu lông Yonex Basic Shorts đen viền xanh',
    brand: 'Yonex',
    category: 'pants',
    categoryName: 'Quần cầu lông',
    price: 229000,
    oldPrice: 320000,
    rating: 4.6,
    reviewsCount: 26,
    imageEmoji: '🩳',
    imageUrl: '/products/p18.jpg',
    isSale: true,
    discountPercent: 28,
    specs: {
      weight: 'Vải nhẹ, ít nhăn, nhanh khô',
      balance: 'Lưng thun dây rút dễ điều chỉnh',
      material: 'Polyester co giãn nhẹ',
      origin: 'Trang phục thể thao Yonex'
    },
    description: 'Quần cầu lông tập luyện form cơ bản, dễ phối áo và không hạn chế biên độ chân khi di chuyển chéo sân.'
  },
  {
    id: 'p19',
    name: 'Túi vợt cầu lông Yonex Pro Tournament 3 ngăn',
    brand: 'Yonex',
    category: 'bag',
    categoryName: 'Túi cầu lông',
    price: 1150000,
    oldPrice: 1450000,
    rating: 4.9,
    reviewsCount: 41,
    imageEmoji: '🎒',
    imageUrl: '/products/p19.jpg',
    galleryImages: ['/products/gallery/p19-gallery-1.webp', '/products/gallery/p19-gallery-2.webp', '/products/gallery/p19-gallery-3.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 21,
    specs: {
      weight: 'Đựng 8-10 vợt, có ngăn giày riêng',
      balance: 'Quai xách và quai đeo vai linh hoạt',
      material: 'Vải PU cao cấp chống thấm nhẹ',
      origin: 'Chính hãng Yonex'
    },
    description: 'Túi cầu lông sức chứa lớn cho người chơi thường xuyên mang nhiều vợt, giày, cầu và quần áo. Thích hợp thi đấu giải phong trào hoặc tập luyện theo đội.'
  },
  {
    id: 'p20',
    name: 'Giày cầu lông Victor A970 Ace trắng xanh',
    brand: 'Victor',
    category: 'shoes',
    categoryName: 'Giày cầu lông',
    price: 2190000,
    oldPrice: 2690000,
    rating: 4.8,
    reviewsCount: 34,
    imageEmoji: '👟',
    imageUrl: '/products/p20.jpg',
    galleryImages: ['/products/gallery/p20-gallery-1.webp', '/products/gallery/p20-gallery-2.webp', '/products/gallery/p20-gallery-3.webp', '/products/gallery/p20-gallery-4.webp'],
    isHot: true,
    isSale: true,
    discountPercent: 19,
    specs: {
      weight: 'Khoảng 300g mỗi chiếc',
      balance: 'Đế giày bám sân tốt, hỗ trợ chuyển hướng nhanh',
      material: 'Thân giày thoáng khí, đệm giữa hấp thụ chấn động',
      origin: 'Chính hãng Victor'
    },
    description: 'Giày cầu lông Victor A970 Ace dành cho người chơi cần độ ổn định và độ bám sân cao. Form chắc chắn, phù hợp di chuyển tốc độ và các pha phòng thủ liên tục.'
  },
  {
    id: 'p21',
    name: 'Áo cầu lông Felet RN3610 đỏ trắng',
    brand: 'Felet',
    category: 'shirt',
    categoryName: 'Áo cầu lông',
    price: 459000,
    oldPrice: 620000,
    rating: 4.7,
    reviewsCount: 17,
    imageEmoji: '👕',
    imageUrl: '/products/p21.jpg',
    isNew: true,
    isSale: true,
    discountPercent: 26,
    specs: {
      weight: 'Áo cầu lông ngắn tay form thể thao',
      balance: 'Form nam nữ, dễ mặc khi tập luyện',
      material: 'Vải thể thao thoáng khí, nhanh khô',
      origin: 'Chính hãng Felet'
    },
    description: 'Áo cầu lông Felet RN3610 với phối màu đỏ trắng nổi bật, chất vải nhẹ và thoáng khí, phù hợp tập luyện cá nhân hoặc làm áo đồng phục đội.'
  },
  {
      id: 'p22',
      name: 'Vợt cầu lông Victor Auraspeed 90K II',
      brand: 'Victor',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 3650000,
      oldPrice: 4290000,
      rating: 4.9,
      reviewsCount: 46,
      imageEmoji: '*',
      imageUrl: '/products/p22.png',
      galleryImages: ['/products/gallery/p22-gallery-1.webp'],
      isHot: true,
      isSale: true,
      discountPercent: 15,
      specs: {
        weight: '4U / 5U',
        balance: 'Cân bằng, tốc độ nhanh',
        tension: 'Tối đa 30 lbs',
        stiffness: 'Cứng',
        material: 'Graphite đàn hồi cao',
        origin: 'Chính hãng Victor'
      },
      description: 'Vợt cầu lông tốc độ cao cho người chơi đánh đôi công nhanh, cần độ ổn định và phản hồi tốt trong các pha phòng thủ liên tục.'
    },
  {
      id: 'p23',
      name: 'Vợt cầu lông Yonex Nanoflare 1000 Game',
      brand: 'Yonex',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 2490000,
      oldPrice: 2990000,
      rating: 4.8,
      reviewsCount: 39,
      imageEmoji: '*',
      imageUrl: '/products/p23.png',
      galleryImages: ['/products/gallery/p23-gallery-1.webp', '/products/gallery/p23-gallery-2.webp', '/products/gallery/p23-gallery-3.webp', '/products/gallery/p23-gallery-4.webp'],
      isNew: true,
      isSale: true,
      discountPercent: 17,
      specs: {
        weight: '4U',
        balance: 'Nhẹ đầu',
        tension: '20 - 28 lbs',
        stiffness: 'Cứng trung bình',
        material: 'Khung graphite',
        origin: 'Chính hãng Yonex'
      },
      description: 'Mẫu vợt thiên tốc độ, dễ xoay trở trong đánh đôi và phù hợp người chơi thích phản tạt nhanh trên lưới.'
    },
  {
      id: 'p24',
      name: 'Vợt cầu lông Li-Ning Halbertec 8000',
      brand: 'Lining',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 3190000,
      oldPrice: 3790000,
      rating: 4.8,
      reviewsCount: 28,
      imageEmoji: '*',
      imageUrl: '/products/p24.jpg',
      galleryImages: ['/products/gallery/p24-gallery-1.webp', '/products/gallery/p24-gallery-3.webp', '/products/gallery/p24-gallery-4.webp'],
      isSale: true,
      discountPercent: 16,
      specs: {
        weight: '4U',
        balance: 'Cân bằng',
        tension: 'Tối đa 31 lbs',
        stiffness: 'Trung bình',
        material: 'Sợi carbon cấp độ cao',
        origin: 'Chính hãng Li-Ning'
      },
      description: 'Dòng vợt công thủ toàn diện với cảm giác đánh chắc, phù hợp người chơi đa dạng lối cầu và cần độ kiểm soát cao.'
    },
  {
      id: 'p25',
      name: 'Vợt cầu lông Yonex Arcsaber 11 Play',
      brand: 'Yonex',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 1190000,
      oldPrice: 1490000,
      rating: 4.7,
      reviewsCount: 64,
      imageEmoji: '*',
      imageUrl: '/products/p25.jpg',
      galleryImages: ['/products/gallery/p25-gallery-1.webp', '/products/gallery/p25-gallery-2.webp'],
      isHot: true,
      isSale: true,
      discountPercent: 20,
      specs: {
        weight: '4U',
        balance: 'Cân bằng',
        tension: '19 - 27 lbs',
        stiffness: 'Trung bình',
        material: 'Graphite',
        origin: 'Dòng Play chính hãng Yonex'
      },
      description: 'Vợt dễ làm quen và nâng cấp kỹ thuật, cảm giác cầu rõ, dùng tốt cho người chơi phong trào cần sự ổn định.'
    },
  {
      id: 'p26',
      name: 'Vợt cầu lông Victor Jetspeed S 12 II',
      brand: 'Victor',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 2990000,
      oldPrice: 3590000,
      rating: 4.8,
      reviewsCount: 33,
      imageEmoji: '*',
      imageUrl: '/products/p26.jpg',
      galleryImages: ['/products/gallery/p26-gallery-1.webp', '/products/gallery/p26-gallery-2.webp', '/products/gallery/p26-gallery-3.webp', '/products/gallery/p26-gallery-4.webp'],
      isSale: true,
      discountPercent: 17,
      specs: {
        weight: '4U',
        balance: 'Hơi nhẹ đầu',
        tension: 'Tối đa 30 lbs',
        stiffness: 'Cứng',
        material: 'Nano Fortify graphite',
        origin: 'Chính hãng Victor'
      },
      description: 'Mẫu Jetspeed đánh nhanh, linh hoạt và rất hợp với người chơi đôi cần vợt gọn, thoát vợt nhanh.'
    },
  {
      id: 'p27',
      name: 'Vợt cầu lông Mizuno Fortius 11 Power',
      brand: 'Mizuno',
      category: 'racket',
      categoryName: 'Vợt cầu lông',
      price: 3490000,
      oldPrice: 4190000,
      rating: 4.7,
      reviewsCount: 18,
      imageEmoji: '*',
      imageUrl: '/products/p27.jpg',
      galleryImages: ['/products/gallery/p27-gallery-1.webp', '/products/gallery/p27-gallery-2.webp', '/products/gallery/p27-gallery-3.webp', '/products/gallery/p27-gallery-4.webp'],
      isNew: true,
      isSale: true,
      discountPercent: 17,
      specs: {
        weight: '4U',
        balance: 'Nặng đầu',
        tension: 'Tối đa 30 lbs',
        stiffness: 'Cứng',
        material: 'Graphite Nhật Bản',
        origin: 'Chính hãng Mizuno'
      },
      description: 'Vợt thiên công cho người chơi thích đập cầu nặng, thân vợt chắc và đầu vợt có độ đầm lực tốt.'
    },
  {
      id: 'p28',
      name: 'Giày cầu lông nam Yonex Power Cushion Aerus Z',
      brand: 'Yonex',
      category: 'shoes',
      categoryName: 'Giày cầu lông',
      price: 2650000,
      oldPrice: 3250000,
      rating: 4.9,
      reviewsCount: 51,
      imageEmoji: '*',
      imageUrl: '/products/p28.jpg',
      galleryImages: ['/products/gallery/p28-gallery-1.webp'],
      isHot: true,
      isSale: true,
      discountPercent: 18,
      specs: {
        weight: 'Siêu nhẹ',
        balance: 'Hỗ trợ bước chân nhanh',
        material: 'Đế giữa Power Cushion',
        origin: 'Chính hãng Yonex'
      },
      description: 'Giày siêu nhẹ dành cho người chơi cần tốc độ và độ linh hoạt cao trong các pha di chuyển liên tục.'
    },
  {
      id: 'p29',
      name: 'Giày cầu lông Victor P9200II TD trắng xanh',
      brand: 'Victor',
      category: 'shoes',
      categoryName: 'Giày cầu lông',
      price: 1890000,
      oldPrice: 2390000,
      rating: 4.8,
      reviewsCount: 37,
      imageEmoji: '*',
      imageUrl: '/products/p29.jpg',
      galleryImages: ['/products/gallery/p29-gallery-1.webp', '/products/gallery/p29-gallery-2.webp', '/products/gallery/p29-gallery-3.webp', '/products/gallery/p29-gallery-4.webp'],
      isSale: true,
      discountPercent: 21,
      specs: {
        weight: 'Khoảng 310g',
        balance: 'Ổn định, chống lật',
        material: 'Đệm EnergyMax',
        origin: 'Chính hãng Victor'
      },
      description: 'Giày cầu lông Victor ổn định, đệm êm và đế bám sân tốt, phù hợp tập luyện hằng ngày.'
    },
  {
      id: 'p30',
      name: 'Giày cầu lông Li-Ning Saga Lite 4 trắng vàng',
      brand: 'Lining',
      category: 'shoes',
      categoryName: 'Giày cầu lông',
      price: 1590000,
      oldPrice: 1990000,
      rating: 4.7,
      reviewsCount: 24,
      imageEmoji: '*',
      imageUrl: '/products/p30.jpg',
      galleryImages: ['/products/gallery/p30-gallery-1.webp', '/products/gallery/p30-gallery-2.webp', '/products/gallery/p30-gallery-3.webp', '/products/gallery/p30-gallery-4.webp'],
      isNew: true,
      isSale: true,
      discountPercent: 20,
      specs: {
        weight: 'Trọng lượng nhẹ',
        balance: 'Di chuyển linh hoạt',
        material: 'Đế cao su không để lại vệt trên sân',
        origin: 'Chính hãng Li-Ning'
      },
      description: 'Giày tập luyện nhẹ, dễ mang và phù hợp người chơi mới nâng cấp lên giày cầu lông chuyên dụng.'
    },
  {
      id: 'p31',
      name: 'Giày cầu lông Mizuno Wave Fang 2 đen vàng',
      brand: 'Mizuno',
      category: 'shoes',
      categoryName: 'Giày cầu lông',
      price: 2790000,
      oldPrice: 3350000,
      rating: 4.8,
      reviewsCount: 29,
      imageEmoji: '*',
      imageUrl: '/products/p31.jpg',
      galleryImages: ['/products/gallery/p31-gallery-2.webp', '/products/gallery/p31-gallery-3.webp', '/products/gallery/p31-gallery-4.webp'],
      isSale: true,
      discountPercent: 17,
      specs: {
        weight: 'Giày thi đấu ổn định',
        balance: 'Hỗ trợ ngang chắc chắn',
        material: 'Tấm đệm Mizuno Wave',
        origin: 'Chính hãng Mizuno'
      },
      description: 'Giày cao cấp với độ ổn định cao, giúp tự tin trong những pha đập nhảy và đổi hướng nhanh.'
    },
  {
      id: 'p32',
      name: 'Áo polo cầu lông Yonex 10453EX xanh navy',
      brand: 'Yonex',
      category: 'shirt',
      categoryName: 'Áo cầu lông',
      price: 390000,
      oldPrice: 520000,
      rating: 4.7,
      reviewsCount: 22,
      imageEmoji: '*',
      imageUrl: '/products/p32.jpg',
      isSale: true,
      discountPercent: 25,
      specs: {
        weight: 'Vải nhanh khô',
        balance: 'Form tiêu chuẩn',
        material: 'Polyester',
        origin: 'Trang phục Yonex'
      },
      description: 'Áo polo thể thao gọn dáng, thoáng khí và dễ phối với quần short cầu lông.'
    },
  {
      id: 'p33',
      name: 'Áo cầu lông Victor T-33102 đỏ đen',
      brand: 'Victor',
      category: 'shirt',
      categoryName: 'Áo cầu lông',
      price: 350000,
      oldPrice: 460000,
      rating: 4.6,
      reviewsCount: 16,
      imageEmoji: '*',
      imageUrl: '/products/p33.jpg',
      isNew: true,
      isSale: true,
      discountPercent: 24,
      specs: {
        weight: 'Vải lưới nhẹ',
        balance: 'Form thể thao',
        material: 'Polyester nhanh khô',
        origin: 'Trang phục Victor'
      },
      description: 'Áo tập luyện Victor màu đỏ đen nổi bật, giữ cảm giác khô thoáng khi vận động cường độ cao.'
    },
  {
      id: 'p34',
      name: 'Áo thi đấu cầu lông Li-Ning AAYT069',
      brand: 'Lining',
      category: 'shirt',
      categoryName: 'Áo cầu lông',
      price: 420000,
      oldPrice: 560000,
      rating: 4.8,
      reviewsCount: 20,
      imageEmoji: '*',
      imageUrl: '/products/p34.jpg',
      isSale: true,
      discountPercent: 25,
      specs: {
        weight: 'Vải thi đấu',
        balance: 'Form thể thao ôm gọn',
        material: 'Polyester spandex',
        origin: 'Trang phục Li-Ning'
      },
      description: 'Áo thi đấu Li-Ning với chất vải mịn, co giãn và hỗ trợ thoát hơi nhanh.'
    },
  {
      id: 'p35',
      name: 'Áo cầu lông đồng đội Felet xanh trắng',
      brand: 'Felet',
      category: 'shirt',
      categoryName: 'Áo cầu lông',
      price: 260000,
      oldPrice: 340000,
      rating: 4.6,
      reviewsCount: 13,
      imageEmoji: '*',
      imageUrl: '/products/p35.jpg',
      isSale: true,
      discountPercent: 24,
      specs: {
        weight: 'Vải áo đồng đội',
        balance: 'Form nam nữ',
        material: 'Polyester nhanh khô',
        origin: 'Trang phục Felet'
      },
      description: 'Áo cầu lông Felet giá tốt, phù hợp may đồng đội hoặc tập luyện hằng tuần.'
    },
  {
      id: 'p36',
      name: 'Váy cầu lông nữ Yonex 26096EX màu xanh',
      brand: 'Yonex',
      category: 'skirt',
      categoryName: 'Váy cầu lông',
      price: 420000,
      oldPrice: 560000,
      rating: 4.8,
      reviewsCount: 18,
      imageEmoji: '*',
      imageUrl: '/products/p36.jpg',
      isNew: true,
      isSale: true,
      discountPercent: 25,
      specs: {
        weight: 'Váy nhẹ',
        balance: 'Có quần trong đi kèm',
        material: 'Polyester co giãn',
        origin: 'Trang phục Yonex'
      },
      description: 'Váy cầu lông nữ màu xanh, form gọn và có quần trong tiện lợi khi thi đấu.'
    },
  {
      id: 'p37',
      name: 'Váy cầu lông nữ Victor K-31300 màu đen',
      brand: 'Victor',
      category: 'skirt',
      categoryName: 'Váy cầu lông',
      price: 390000,
      oldPrice: 510000,
      rating: 4.7,
      reviewsCount: 14,
      imageEmoji: '*',
      imageUrl: '/products/p37.jpg',
      isSale: true,
      discountPercent: 24,
      specs: {
        weight: 'Vải mềm co giãn',
        balance: 'Lưng váy ôm chắc',
        material: 'Polyester spandex',
        origin: 'Trang phục Victor'
      },
      description: 'Váy thể thao Victor màu đen dễ phối đồ, linh hoạt trong các bước di chuyển chéo sân.'
    },
  {
      id: 'p38',
      name: 'Váy cầu lông nữ Li-Ning AAPQ',
      brand: 'Lining',
      category: 'skirt',
      categoryName: 'Váy cầu lông',
      price: 360000,
      oldPrice: 480000,
      rating: 4.6,
      reviewsCount: 12,
      imageEmoji: '*',
      imageUrl: '/products/p38.jpg',
      isSale: true,
      discountPercent: 25,
      specs: {
        weight: 'Váy thoáng khí',
        balance: 'Lưng váy linh hoạt',
        material: 'Polyester pha sợi co giãn',
        origin: 'Trang phục Li-Ning'
      },
      description: 'Váy tập luyện Li-Ning thiết kế năng động, phù hợp tập luyện và thi đấu phong trào.'
    },
  {
      id: 'p39',
      name: 'Quần cầu lông Yonex 15150EX màu đen',
      brand: 'Yonex',
      category: 'pants',
      categoryName: 'Quần cầu lông',
      price: 310000,
      oldPrice: 420000,
      rating: 4.7,
      reviewsCount: 30,
      imageEmoji: '*',
      imageUrl: '/products/p39.jpg',
      isSale: true,
      discountPercent: 26,
      specs: {
        weight: 'Quần short nhẹ',
        balance: 'Lưng thun co giãn',
        material: 'Polyester',
        origin: 'Trang phục Yonex'
      },
      description: 'Quần short cầu lông form cơ bản, dễ mặc và thích hợp mọi buổi tập.'
    },
  {
      id: 'p40',
      name: 'Quần cầu lông Victor R-40200 xanh navy',
      brand: 'Victor',
      category: 'pants',
      categoryName: 'Quần cầu lông',
      price: 280000,
      oldPrice: 370000,
      rating: 4.6,
      reviewsCount: 19,
      imageEmoji: '*',
      imageUrl: '/products/p40.jpg',
      isNew: true,
      isSale: true,
      discountPercent: 24,
      specs: {
        weight: 'Quần nhanh khô',
        balance: 'Form thể thao thoải mái',
        material: 'Polyester',
        origin: 'Trang phục Victor'
      },
      description: 'Quần Victor màu navy gọn gàng, không bị bó khi chạy sân và bật nhảy.'
    },
  {
      id: 'p41',
      name: 'Quần cầu lông Li-Ning AKSR màu đen',
      brand: 'Lining',
      category: 'pants',
      categoryName: 'Quần cầu lông',
      price: 260000,
      oldPrice: 350000,
      rating: 4.6,
      reviewsCount: 22,
      imageEmoji: '*',
      imageUrl: '/products/p41-v2.jpg',
      isSale: true,
      discountPercent: 26,
      specs: {
        weight: 'Vải khô nhanh',
        balance: 'Form tập luyện',
        material: 'Polyester co giãn',
        origin: 'Trang phục Li-Ning'
      },
      description: 'Quần cầu lông Li-Ning có dây rút, chất vải nhẹ và dễ phối với áo đội tuyển.'
    },
  {
      id: 'p42',
      name: 'Túi vợt cầu lông Yonex BA92426EX Pro chứa 6 vợt',
      brand: 'Yonex',
      category: 'bag',
      categoryName: 'Túi cầu lông',
      price: 1690000,
      oldPrice: 2090000,
      rating: 4.9,
      reviewsCount: 33,
      imageEmoji: '*',
      imageUrl: '/products/p42.jpg',
      galleryImages: ['/products/gallery/p42-gallery-1.webp', '/products/gallery/p42-gallery-2.webp', '/products/gallery/p42-gallery-3.webp'],
      isHot: true,
      isSale: true,
      discountPercent: 19,
      specs: {
        weight: 'Sức chứa 6 vợt',
        balance: 'Ngăn giữ nhiệt',
        material: 'PU polyester',
        origin: 'Túi Yonex chính hãng'
      },
      description: 'Túi vợt Yonex Pro có sức chứa lớn, ngăn sắp xếp rõ ràng cho vợt, giày và phụ kiện.'
    },
  {
      id: 'p43',
      name: 'Túi vợt cầu lông Victor BR9609 đen đỏ',
      brand: 'Victor',
      category: 'bag',
      categoryName: 'Túi cầu lông',
      price: 1290000,
      oldPrice: 1650000,
      rating: 4.8,
      reviewsCount: 27,
      imageEmoji: '*',
      imageUrl: '/products/p43.jpg',
      galleryImages: ['/products/gallery/p43-gallery-1.webp'],
      isSale: true,
      discountPercent: 22,
      specs: {
        weight: '2 ngăn chính',
        balance: 'Có ngăn giày riêng',
        material: 'Polyester bền chắc',
        origin: 'Túi Victor chính hãng'
      },
      description: 'Túi vợt Victor màu đen đỏ, sức chứa tốt và quai đeo êm vai cho người đi sân thường xuyên.'
    },
  {
      id: 'p44',
      name: 'Túi vợt cầu lông Li-Ning ABJT 6 trong 1',
      brand: 'Lining',
      category: 'bag',
      categoryName: 'Túi cầu lông',
      price: 990000,
      oldPrice: 1290000,
      rating: 4.7,
      reviewsCount: 20,
      imageEmoji: '*',
      imageUrl: '/products/p44.jpg',
      galleryImages: ['/products/gallery/p44-gallery-1.webp', '/products/gallery/p44-gallery-2.webp', '/products/gallery/p44-gallery-3.webp', '/products/gallery/p44-gallery-4.webp'],
      isNew: true,
      isSale: true,
      discountPercent: 23,
      specs: {
        weight: 'Sức chứa 6 vợt',
        balance: 'Các ngăn phụ kiện riêng biệt',
        material: 'Vải chống thấm nhẹ',
        origin: 'Túi Li-Ning chính hãng'
      },
      description: 'Túi cầu lông Li-Ning thiết kế thể thao, đủ ngăn chứa cho cả tập luyện và thi đấu phong trào.'
    },
  {
      id: 'p45',
      name: 'Balo cầu lông Yonex Pro Backpack 92412EX',
      brand: 'Yonex',
      category: 'backpack',
      categoryName: 'Balo cầu lông',
      price: 950000,
      oldPrice: 1190000,
      rating: 4.8,
      reviewsCount: 25,
      imageEmoji: '*',
      imageUrl: '/products/p45.jpg',
      isSale: true,
      discountPercent: 20,
      specs: {
        weight: 'Ngăn chứa vợt trong balo',
        balance: 'Có ngăn giày',
        material: 'Polyester PU',
        origin: 'Balo Yonex chính hãng'
      },
      description: 'Balo Yonex Pro gọn, đựng đủ đồ tập luyện và có ngăn bảo vệ vợt tiện lợi.'
    },
  {
      id: 'p46',
      name: 'Balo cầu lông Victor BR8009 đen xanh',
      brand: 'Victor',
      category: 'backpack',
      categoryName: 'Balo cầu lông',
      price: 820000,
      oldPrice: 1050000,
      rating: 4.7,
      reviewsCount: 18,
      imageEmoji: '*',
      imageUrl: '/products/p46.jpg',
      galleryImages: ['/products/gallery/p46-gallery-1.webp', '/products/gallery/p46-gallery-2.webp', '/products/gallery/p46-gallery-3.webp', '/products/gallery/p46-gallery-4.webp'],
      isNew: true,
      isSale: true,
      discountPercent: 22,
      specs: {
        weight: 'Balo tập luyện hằng ngày',
        balance: 'Đệm lưng thoải mái',
        material: 'Polyester',
        origin: 'Balo Victor chính hãng'
      },
      description: 'Balo cầu lông Victor phù hợp đi sân hằng ngày, nhiều ngăn phụ kiện và kiểu dáng gọn.'
    },
  {
      id: 'p47',
      name: 'Balo cầu lông Li-Ning ABSS trắng đen',
      brand: 'Lining',
      category: 'backpack',
      categoryName: 'Balo cầu lông',
      price: 720000,
      oldPrice: 930000,
      rating: 4.6,
      reviewsCount: 16,
      imageEmoji: '*',
      imageUrl: '/products/p47.jpg',
      galleryImages: ['/products/gallery/p47-gallery-1.webp'],
      isSale: true,
      discountPercent: 23,
      specs: {
        weight: 'Balo nhỏ gọn',
        balance: 'Có túi hông',
        material: 'Vải bền chắc',
        origin: 'Balo Li-Ning chính hãng'
      },
      description: 'Balo Li-Ning giá tốt, dễ đựng vợt và phụ kiện cho người chơi tập luyện cơ bản.'
    },
  {
      id: 'p48',
      name: 'Ống cầu lông lông vũ Yonex Aerosensa 30',
      brand: 'Yonex',
      category: 'accessories',
      categoryName: 'Phụ kiện cầu lông',
      price: 690000,
      oldPrice: 790000,
      rating: 4.9,
      reviewsCount: 62,
      imageEmoji: '*',
      imageUrl: '/products/p48.png',
      isHot: true,
      isSale: true,
      discountPercent: 13,
      specs: {
        weight: '12 quả cầu mỗi ống',
        balance: 'Đường bay chuẩn thi đấu',
        material: 'Lông vũ và đế bần',
        origin: 'Cầu lông Yonex chính hãng'
      },
      description: 'Cầu lông lông vũ Yonex Aerosensa 30 bay ổn định, thích hợp thi đấu và tập luyện chất lượng cao.'
    },
  {
      id: 'p49',
      name: 'Ống cầu lông Victor Master Ace',
      brand: 'Victor',
      category: 'accessories',
      categoryName: 'Phụ kiện cầu lông',
      price: 520000,
      oldPrice: 620000,
      rating: 4.8,
      reviewsCount: 44,
      imageEmoji: '*',
      imageUrl: '/products/p49.jpg',
      isSale: true,
      discountPercent: 16,
      specs: {
        weight: '12 quả cầu mỗi ống',
        balance: 'Đường bay ổn định',
        material: 'Lông vũ và đế bần',
        origin: 'Cầu lông Victor chính hãng'
      },
      description: 'Cầu Victor Master Ace có độ bay ổn định, phù hợp tập luyện nâng cao và thi đấu phong trào.'
    },
  {
      id: 'p50',
      name: 'Quấn cán Yonex Super Grap AC102 nhiều màu',
      brand: 'Yonex',
      category: 'accessories',
      categoryName: 'Phụ kiện cầu lông',
      price: 95000,
      oldPrice: 120000,
      rating: 4.8,
      reviewsCount: 91,
      imageEmoji: '*',
      imageUrl: '/products/p50.jpg',
      isNew: true,
      isSale: true,
      discountPercent: 21,
      specs: {
        weight: '3 cuộn mỗi gói',
        balance: 'Cảm giác bám tay',
        material: 'Quấn cán PU',
        origin: 'Quấn cán Yonex chính hãng'
      },
      description: 'Quấn cán Yonex Super Grap cầm chắc tay, hút mồ hôi tốt và dễ thay thế cho vợt tập luyện hằng ngày.'
    },
  {
      id: 'p51',
      name: 'Quấn cán cầu lông Victor GR262 màu đen',
      brand: 'Victor',
      category: 'accessories',
      categoryName: 'Phụ kiện cầu lông',
      price: 85000,
      oldPrice: 110000,
      rating: 4.7,
      reviewsCount: 58,
      imageEmoji: '*',
      imageUrl: '/products/p51.jpg',
      isSale: true,
      discountPercent: 23,
      specs: {
        weight: 'Một cuộn quấn cán',
        balance: 'Cảm giác chạm mềm',
        material: 'Quấn cán PU',
        origin: 'Quấn cán Victor chính hãng'
      },
      description: 'Quấn cán Victor giá tốt, giúp cầm vợt chắc hơn và hạn chế trơn tay khi ra mồ hôi.'
    }
];

export interface StringProduct {
  id: string;
  name: string;
  brand: string;
  diameter: string;
  feel: string;
  repulsion: string;
  durability: string;
  price: number;
  bestFor: string;
  imageUrl: string;
}

export const STRINGS: StringProduct[] = [
  {
    id: 's0',
    name: 'Cước phổ thông',
    brand: 'No brand',
    diameter: '0.72 mm',
    feel: 'Cứng, chịu bền',
    repulsion: '★★★☆☆',
    durability: '★★★★★',
    price: 40000,
    bestFor: 'Giá rẻ, tập luyện cơ bản, không yêu cầu cao',
    imageUrl: '/products/p4.png',
  },
  {
    id: 's1',
    name: 'Yonex BG 65 Titanium',
    brand: 'Yonex',
    diameter: '0.70 mm',
    feel: 'Cứng trung bình',
    repulsion: '★★★★☆',
    durability: '★★★★★',
    price: 180000,
    bestFor: 'Bền, tiết kiệm, tập luyện hằng ngày',
    imageUrl: '/products/p4.png',
  },
  {
    id: 's2',
    name: 'Yonex BG 80',
    brand: 'Yonex',
    diameter: '0.68 mm',
    feel: 'Mềm, cảm giác tốt',
    repulsion: '★★★★★',
    durability: '★★★☆☆',
    price: 220000,
    bestFor: 'Nảy mạnh, kiểm soát tốt, phong trào – thi đấu',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 's3',
    name: 'Yonex NBG 99',
    brand: 'Yonex',
    diameter: '0.69 mm',
    feel: 'Mềm nhún',
    repulsion: '★★★★★',
    durability: '★★★★☆',
    price: 280000,
    bestFor: 'Thi đấu, kiểm soát đường cầu chuẩn xác',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 's4',
    name: 'Victor VS-850',
    brand: 'Victor',
    diameter: '0.66 mm',
    feel: 'Mềm, nhẹ tay',
    repulsion: '★★★★★',
    durability: '★★★☆☆',
    price: 170000,
    bestFor: 'Đánh lưới, phản tạt, lực tay nhẹ',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 's5',
    name: 'Victor VBS-66N',
    brand: 'Victor',
    diameter: '0.66 mm',
    feel: 'Cứng, âm nổ đanh',
    repulsion: '★★★★☆',
    durability: '★★★★☆',
    price: 190000,
    bestFor: 'Đập mạnh, thi đấu cường độ cao',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 's6',
    name: 'Li-Ning No.1',
    brand: 'Lining',
    diameter: '0.70 mm',
    feel: 'Cứng, bền',
    repulsion: '★★★★☆',
    durability: '★★★★★',
    price: 150000,
    bestFor: 'Giá tốt, bền bỉ, tập luyện phong trào',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=400&q=80',
  },
];

export const UTILS = {
  formatCurrency: (value: number) => {
    return new Intl.NumberFormat('vi-VN', {
      style: 'currency',
      currency: 'VND'
    }).format(value);
  }
};
